### ISSUE TITLE
Watch face loses its settings after a tap

### ISSUE THREAD

**Issue by amroibrahim** [johnmillage/FancyFace#1]
If you set a color, or temperature to C, those settings get lost after a tap "shake"

**Comment by johnmillage** [comment]
Which version of the watch are you using?

**Comment by amroibrahim** [comment]
the one listed on pebble site, it says v1.4.
Thanx so much for sharing such wonderful source code. The code is well written and easy to read, you have done a lot of effort to bring this to pebble community. Great work. 
Thank you.

**Comment by johnmillage** [comment]
Thanks. I meant what version of the watch (Original Pebble, Pebble Time,
Pebble Steel) are you seeing the issue on?

**Comment by amroibrahim** [comment]
pebble time steel

**Comment by johnmillage** [comment]
Thats so wierd.  I use the pebble time and have no issues but you are the
second person with the steel to have this issue.

**Comment by amroibrahim** [comment]
I will try and see if I can find where the bug is, Initially it seems related how the setting are saved and sent to pebble.

**Comment by johnmillage** [comment]
I would really appreaciate it since i don't have a steel to test on.  I
know it works fine on my pebble time.  I asked developer support about it
also.

**Comment by amroibrahim** [comment]
At the moment cloudpebble.net is down and wont let me connect so I can't test my theory. Please note that this is the first time I'm working with pebble SDK so my conclusions might be wrong. With that being said, I thinking in the "init" function you have "accel_tap_service_subscribe(handle_tap);" this means the function "handle_tap" will be called no matter if  "All" color scheme is selected or not.
"handle_tap" function doesn't also check if the "All" color is selected or not. 

Solution 1:
If you wan't to keep every thing the way as it is you will need to add an if statement in "handle_tap"  function to check if the user has selected "All" color scheme, and if he did, you need to return and not execute the function.

Solution 2: The better option
if user selects All, you really don't need to subscribe for a tap. You might need to move "accel_tap_service_subscribe(handle_tap)" out side of the init function and subscribe and unsubscribe based on used selection of color scheme.
I believe that this is the better solution because will have a positive impact on battery life if the user want to stick to one scheme.

Please correct me if I'm wrong, and let me know what you think. 
Note: I will try to get a VM installed and the get the SDK installed locally for testing, but that might take some time.

**Comment by johnmillage** [comment]
Well you are right that handle_tap is called no matter what.  But that is
not a problem.  Notice that handle_tap then calls set_color_scheme.  In
set_color_scheme i do a bunch of checks on s_cur_color_type (which is an
integer representing the color the user picked in the settings) and
set s_cur_color_scheme (the integer i actually use to pick the colors for
drawing).  When the s_cur_color_type is one of the colors (integers 4-8) i
just set s_cur_color_scheme to the correct value.  So even though
handle_tap is called it will have no effect.  I know that this code works
because I use this on my pebble time every day and i have it set to a
specific color.  I really think it must have something to do with the time
steel but i don't know what it could be.

I think the best way to troubleshoot is logging.  If your up to it and can
install on your watch via cloudpebble, i would say add this logging in
handle_tap in place of the set_color_scheme() call

APP_LOG(APP_LOG_LEVEL_INFO, "before set %d %d", (int)s_cur_color_scheme,
(int) s_cur_color_type);
set_color_scheme();
APP_LOG(APP_LOG_LEVEL_INFO, "after set %d %d", (int)s_cur_color_scheme,
(int) s_cur_color_type);

and see if it is printing out the expected results.  (which would be that
s_cur_color_type is always being changed to the same value).

Let me know if you have question.  And again thanks for all your help.

**Comment by amroibrahim** [comment]
[INFO] FancyFace.c:667: got 0
[INFO] FancyFace.c:667: got 4
[INFO] FancyFace.c:667: got 1
[INFO] FancyFace.c:667: got 2
[INFO] FancyFace.c:667: got 3
[INFO] FancyFace.c:626: tap 2 -1
[INFO] FancyFace.c:632: before set 1 0
[INFO] FancyFace.c:634: after set 1 0
[INFO] FancyFace.c:626: tap 2 -1
[INFO] FancyFace.c:632: before set 2 0
[INFO] FancyFace.c:634: after set 2 0
[INFO] FancyFace.c:626: tap 1 -1
[INFO] FancyFace.c:632: before set 3 0
[INFO] FancyFace.c:634: after set 3 0
[INFO] FancyFace.c:626: tap 1 -1
[INFO] FancyFace.c:632: before set 4 0
[INFO] FancyFace.c:634: after set 4 0
[INFO] FancyFace.c:626: tap 1 -1
[INFO] FancyFace.c:632: before set 5 0
[INFO] FancyFace.c:634: after set 5 0
[INFO] FancyFace.c:626: tap 1 -1
[INFO] FancyFace.c:632: before set 0 0
[INFO] FancyFace.c:634: after set 0 0
[INFO] FancyFace.c:626: tap 1 1
[INFO] FancyFace.c:632: before set 1 0
[INFO] FancyFace.c:634: after set 1 0

**Comment by amroibrahim** [comment]
How can i see the watch face setting menu to select color while debugging from cloud pebble

**Comment by johnmillage** [comment]
ok your s_cur_color_type is 0 (ALL) which makes sense for what it shows.
Did you set to a specific color in the settings?

**Comment by johnmillage** [comment]
you have to do it on your phone after you install it on the watch.

**Comment by amroibrahim** [comment]
I tried that, but the new trace I added don't show which make me think once i change setting original unmodified binary takes over

**Comment by johnmillage** [comment]
no, it shouldn't.  In fact once you install it from cloudpebble you should
only have that version and not the original from the app store.  so after
you changed the setting the traces stopped completely?

**Comment by amroibrahim** [comment]
[INFO] FancyFace.c:840: main
[INFO] FancyFace.c:811: init
[INFO] FancyFace.c:700: before load 0
[INFO] FancyFace.c:723: after load 1
[INFO] FancyFace.c:667: got 0
[INFO] FancyFace.c:667: got 4
[INFO] FancyFace.c:667: got 1
[INFO] FancyFace.c:667: got 2
[INFO] FancyFace.c:667: got 3
[PHONE] pebble-app.js:?: {'runhost client uuid' = 00000000-0000-0000-0000-000000000000}:{'webapp uuid' = 3477f558-4302-49f1-abd7-2a0963af9d19}: ++_JS_LIFECYCLE_++:LAUNCHING
[INFO] FancyFace.c:620: requesting weather 2 2
[INFO] FancyFace.c:609: sent
[PHONE] pebble-app.js:?: FancyFace__0.0/pebble-js-app.js:47 connect!
[PHONE] pebble-app.js:?: FancyFace__0.0/pebble-js-app.js:50 ready
[PHONE] pebble-app.js:?: {'runhost client uuid' = 49e1ebe2-c21a-44bc-a0e5-ebbe96bcf026}:{'webapp uuid' = 3477f558-4302-49f1-abd7-2a0963af9d19}: ++_JS_LIFECYCLE_++:READY-RUNNING
[PHONE] pebble-app.js:?: FancyFace__0.0/pebble-js-app.js:8 {"coord":{"lon":-93.7,"lat":41.67},"weather":[{"id":800,"main":"Clear","description":"sky is clear","icon":"01n"}],"base":"cmc stations","main":{"temp":59.9,"pressure":1018,"humidity":59,"temp_min":55.4,"temp_max":66.2},"wind":{"speed":7.78,"deg":140},"clouds":{"all":1},"dt":1442803457,"sys":{"type":1,"id":865,"message":0.0058,"country":"US","sunrise":1442836866,"sunset":1442880835},"id":4862760,"name":"Johnston","cod":200}

[PHONE] pebble-app.js:?: FancyFace__0.0/pebble-js-app.js:12 60
[PHONE] pebble-app.js:?: FancyFace__0.0/pebble-js-app.js:13 1
[INFO] FancyFace.c:667: got 0
[INFO] FancyFace.c:667: got 4
[INFO] FancyFace.c:667: got 1
[INFO] FancyFace.c:667: got 2
[INFO] FancyFace.c:667: got 3
[INFO] FancyFace.c:626: tap 1 -1
[INFO] FancyFace.c:632: before set 2 0
[INFO] FancyFace.c:634: after set 2 0
[DEBUG] FancyFace.c:663: App Message Sync Error: APP_MSG_SEND_TIMEOUT
[INFO] FancyFace.c:626: tap 1 1
[INFO] FancyFace.c:632: before set 3 0
[INFO] FancyFace.c:634: after set 3 0
[INFO] FancyFace.c:626: tap 2 1
[INFO] FancyFace.c:632: before set 4 0
[INFO] FancyFace.c:634: after set 4 0
[INFO] ocess_manager.c:369: Heap Usage for App <FancyFace>: Total Size <58172B> Used <1136B> Still allocated <332B>
[PHONE] pebble-app.js:?: {'runhost client uuid' = 49e1ebe2-c21a-44bc-a0e5-ebbe96bcf026}:{'webapp uuid' = 3477f558-4302-49f1-abd7-2a0963af9d19}: ++_JS_LIFECYCLE_++:KILLED
[INFO] fancy_face.c:837: main
[INFO] fancy_face.c:808: init
[INFO] fancy_face.c:697: before load 0
[INFO] fancy_face.c:720: after load 5
[PHONE] pebble-app.js:?: {'runhost client uuid' = 00000000-0000-0000-0000-000000000000}:{'webapp uuid' = 8cb60441-3eb3-47b1-a6eb-d35b3f1f4a33}: ++_JS_LIFECYCLE_++:LAUNCHING
[INFO] fancy_face.c:664: got 0
[INFO] fancy_face.c:664: got 4
[INFO] fancy_face.c:664: got 1
[INFO] fancy_face.c:664: got 2
[INFO] fancy_face.c:664: got 3
[INFO] fancy_face.c:620: requesting weather 2 2
[INFO] fancy_face.c:609: sent
[PHONE] pebble-app.js:?: {'runhost client uuid' = 1b11e234-82a2-4cac-bd8e-6403bc37a6ce}:{'webapp uuid' = 8cb60441-3eb3-47b1-a6eb-d35b3f1f4a33}: ++_JS_LIFECYCLE_++:READY-RUNNING
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:47 connect!
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:50 ready
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:65 Showing configuration page: https://cdn.rawgit.com/johnmillage/FancyFace/f2da62db3d29b3a9c1a3f5bb1c53e61199138cb7/PebbleConfig.html
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:8 {"coord":{"lon":-93.7,"lat":41.67},"weather":[{"id":800,"main":"Clear","description":"sky is clear","icon":"01n"}],"base":"cmc stations","main":{"temp":59.9,"pressure":1018,"humidity":59,"temp_min":55.4,"temp_max":66.2},"wind":{"speed":7.78,"deg":140},"clouds":{"all":1},"dt":1442803457,"sys":{"type":1,"id":865,"message":0.0058,"country":"US","sunrise":1442836866,"sunset":1442880835},"id":4862760,"name":"Johnston","cod":200}

[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:12 60
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:13 1
[INFO] fancy_face.c:664: got 4
[INFO] fancy_face.c:664: got 1
[INFO] fancy_face.c:664: got 0
[INFO] fancy_face.c:664: got 2
[INFO] fancy_face.c:664: got 3
[DEBUG] fancy_face.c:660: App Message Sync Error: APP_MSG_SEND_TIMEOUT
[PHONE] pebble-app.js:?: {'runhost client uuid' = dfd500cb-3607-4e26-8a84-0b5f86a9d5f9}:{'webapp uuid' = dfd500cb-3607-4e26-8a84-0b5f86a9d5f9}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = dfd500cb-3607-4e26-8a84-0b5f86a9d5f9}:{'webapp uuid' = dfd500cb-3607-4e26-8a84-0b5f86a9d5f9}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:72 Configuration page returned: {"background_color":"Darks","temperature_type":"Celsius"}
[INFO] fancy_face.c:664: got 3
[INFO] fancy_face.c:664: got 2
[INFO] fancy_face.c:664: got 4
[INFO] fancy_face.c:664: got 1
[INFO] fancy_face.c:664: got 0
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:91 Send successful: {"PHONE_COLOR_KEY":1,"PHONE_TEMP_TYPE_KEY":1}
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:626: tap 2 1
[INFO] fancy_face.c:626: tap 1 -1
[INFO] fancy_face.c:626: tap 1 -1
[INFO] fancy_face.c:626: tap 2 -1

**Comment by amroibrahim** [comment]
in the above trace this is what i did exactly.
1. Install watch face from pebble app store, change setting to dark.
2. go to pebble cloud, install app. on my watch. (it doesnt start with the dark color)
3. do some taps to show in log
4. I use watch face setting to change it to dark.
4. do some taps, the new trace logs dont show any more

**Comment by johnmillage** [comment]
I don't think you should install from app store at all.  You just go to
cloudpebble and in compilation make sure you select phone [image: Inline
image 1]
and then hit install and run and then it will bring up a dialog and select
view app logs.

**Comment by amroibrahim** [comment]
okay now I dont know what to say, I think the ur watch face function 100% correctly. I think the confusion is that I was selecting dark for black, where it mostly meant it will cycle dark themes. You need to chang the wording to make it clear to the user.

**Comment by amroibrahim** [comment]
[INFO] ocess_manager.c:369: Heap Usage for App <Fancy Face: Total Size <58172B> Used <1136B> Still allocated <332B>
[INFO] fancy_face.c:840: main
[INFO] fancy_face.c:811: init
[INFO] fancy_face.c:700: before load 0
[INFO] fancy_face.c:723: after load 0
[INFO] fancy_face.c:667: got 0
[INFO] fancy_face.c:667: got 4
[INFO] fancy_face.c:667: got 1
[INFO] fancy_face.c:667: got 2
[INFO] fancy_face.c:667: got 3
[INFO] fancy_face.c:620: requesting weather 6 36
[INFO] fancy_face.c:609: sent
[DEBUG] fancy_face.c:663: App Message Sync Error: APP_MSG_SEND_TIMEOUT
[PHONE] pebble-app.js:?: {'runhost client uuid' = 00000000-0000-0000-0000-000000000000}:{'webapp uuid' = 8cb60441-3eb3-47b1-a6eb-d35b3f1f4a33}: ++_JS_LIFECYCLE_++:LAUNCHING
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:47 connect!
[PHONE] pebble-app.js:?: {'runhost client uuid' = 7132f407-70ee-4533-b33b-7c3f3a971d93}:{'webapp uuid' = 8cb60441-3eb3-47b1-a6eb-d35b3f1f4a33}: ++_JS_LIFECYCLE_++:READY-RUNNING
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:50 ready
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:8 {"coord":{"lon":-93.7,"lat":41.67},"weather":[{"id":800,"main":"Clear","description":"sky is clear","icon":"01n"}],"base":"cmc stations","main":{"temp":59.9,"pressure":1018,"humidity":59,"temp_min":55.4,"temp_max":66.2},"wind":{"speed":7.78,"deg":140},"clouds":{"all":1},"dt":1442803457,"sys":{"type":1,"id":865,"message":0.0058,"country":"US","sunrise":1442836866,"sunset":1442880835},"id":4862760,"name":"Johnston","cod":200}

[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:13 1
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:12 60
[INFO] fancy_face.c:667: got 4
[INFO] fancy_face.c:667: got 1
[INFO] fancy_face.c:667: got 0
[INFO] fancy_face.c:667: got 2
[INFO] fancy_face.c:667: got 3
[INFO] fancy_face.c:626: tap 0 -1
[INFO] fancy_face.c:632: before set 1 2
[INFO] fancy_face.c:634: after set 3 2
[INFO] fancy_face.c:626: tap 1 -1
[INFO] fancy_face.c:632: before set 4 2
[INFO] fancy_face.c:634: after set 4 2
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:65 Showing configuration page: https://cdn.rawgit.com/johnmillage/FancyFace/f2da62db3d29b3a9c1a3f5bb1c53e61199138cb7/PebbleConfig.html
[PHONE] pebble-app.js:?: {'runhost client uuid' = 27189cf2-3440-4f46-9daa-37ed8debdb6d}:{'webapp uuid' = 27189cf2-3440-4f46-9daa-37ed8debdb6d}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = 27189cf2-3440-4f46-9daa-37ed8debdb6d}:{'webapp uuid' = 27189cf2-3440-4f46-9daa-37ed8debdb6d}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:72 Configuration page returned: {"background_color":"Darks","temperature_type":"Celsius"}
[INFO] fancy_face.c:667: got 3
[INFO] fancy_face.c:667: got 2
[INFO] fancy_face.c:667: got 4
[INFO] fancy_face.c:667: got 1
[INFO] fancy_face.c:667: got 0
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:91 Send successful: {"PHONE_COLOR_KEY":1,"PHONE_TEMP_TYPE_KEY":1}
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:65 Showing configuration page: https://cdn.rawgit.com/johnmillage/FancyFace/f2da62db3d29b3a9c1a3f5bb1c53e61199138cb7/PebbleConfig.html
[PHONE] pebble-app.js:?: {'runhost client uuid' = 508dc86c-b8b4-46e3-87fb-804e26089a27}:{'webapp uuid' = 508dc86c-b8b4-46e3-87fb-804e26089a27}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = 508dc86c-b8b4-46e3-87fb-804e26089a27}:{'webapp uuid' = 508dc86c-b8b4-46e3-87fb-804e26089a27}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:72 Configuration page returned: {"background_color":"Darks","temperature_type":"Celsius"}
[INFO] fancy_face.c:667: got 3
[INFO] fancy_face.c:667: got 2
[INFO] fancy_face.c:667: got 4
[INFO] fancy_face.c:667: got 1
[INFO] fancy_face.c:667: got 0
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:632: before set 0 1
[INFO] fancy_face.c:634: after set 1 1
[INFO] fancy_face.c:626: tap 1 -1
[INFO] fancy_face.c:632: before set 2 1
[INFO] fancy_face.c:634: after set 2 1
[INFO] fancy_face.c:626: tap 1 -1
[INFO] fancy_face.c:632: before set 3 1
[INFO] fancy_face.c:634: after set 5 1
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:91 Send successful: {"PHONE_COLOR_KEY":1,"PHONE_TEMP_TYPE_KEY":1}
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:632: before set 0 1
[INFO] fancy_face.c:634: after set 1 1
[INFO] fancy_face.c:626: tap 1 -1
[INFO] fancy_face.c:632: before set 2 1
[INFO] fancy_face.c:634: after set 2 1
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 3 1
[INFO] fancy_face.c:634: after set 5 1
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:632: before set 0 1
[INFO] fancy_face.c:634: after set 1 1
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:632: before set 2 1
[INFO] fancy_face.c:634: after set 2 1
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:632: before set 3 1
[INFO] fancy_face.c:634: after set 5 1
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:65 Showing configuration page: https://cdn.rawgit.com/johnmillage/FancyFace/f2da62db3d29b3a9c1a3f5bb1c53e61199138cb7/PebbleConfig.html
[PHONE] pebble-app.js:?: {'runhost client uuid' = 8d69a9fc-3645-4b8d-acd8-433e0564e7c9}:{'webapp uuid' = 8d69a9fc-3645-4b8d-acd8-433e0564e7c9}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = 8d69a9fc-3645-4b8d-acd8-433e0564e7c9}:{'webapp uuid' = 8d69a9fc-3645-4b8d-acd8-433e0564e7c9}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:72 Configuration page returned: {"background_color":"Green","temperature_type":"Celsius"}
[INFO] fancy_face.c:667: got 3
[INFO] fancy_face.c:667: got 2
[INFO] fancy_face.c:667: got 4
[INFO] fancy_face.c:667: got 1
[INFO] fancy_face.c:667: got 0
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:632: before set 5 7
[INFO] fancy_face.c:634: after set 4 7
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:91 Send successful: {"PHONE_COLOR_KEY":7,"PHONE_TEMP_TYPE_KEY":1}
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:632: before set 5 7
[INFO] fancy_face.c:634: after set 4 7
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:632: before set 5 7
[INFO] fancy_face.c:634: after set 4 7
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:632: before set 5 7
[INFO] fancy_face.c:634: after set 4 7
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 5 7
[INFO] fancy_face.c:634: after set 4 7
[INFO] fancy_face.c:626: tap 1 -1
[INFO] fancy_face.c:632: before set 5 7
[INFO] fancy_face.c:634: after set 4 7
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:65 Showing configuration page: https://cdn.rawgit.com/johnmillage/FancyFace/f2da62db3d29b3a9c1a3f5bb1c53e61199138cb7/PebbleConfig.html
[PHONE] pebble-app.js:?: {'runhost client uuid' = f4b29449-e0a3-47a7-abaa-2b680b930411}:{'webapp uuid' = f4b29449-e0a3-47a7-abaa-2b680b930411}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = f4b29449-e0a3-47a7-abaa-2b680b930411}:{'webapp uuid' = f4b29449-e0a3-47a7-abaa-2b680b930411}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:72 Configuration page returned: {"background_color":"Darks","temperature_type":"Fahrenheit"}
[INFO] fancy_face.c:667: got 3
[INFO] fancy_face.c:667: got 2
[INFO] fancy_face.c:667: got 4
[INFO] fancy_face.c:667: got 1
[INFO] fancy_face.c:667: got 0
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:91 Send successful: {"PHONE_COLOR_KEY":1,"PHONE_TEMP_TYPE_KEY":0}
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 0 1
[INFO] fancy_face.c:634: after set 1 1
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 2 1
[INFO] fancy_face.c:634: after set 2 1
[INFO] fancy_face.c:626: tap 1 -1
[INFO] fancy_face.c:632: before set 3 1
[INFO] fancy_face.c:634: after set 5 1
[INFO] fancy_face.c:626: tap 1 -1
[INFO] fancy_face.c:632: before set 0 1
[INFO] fancy_face.c:634: after set 1 1
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 2 1
[INFO] fancy_face.c:634: after set 2 1
[INFO] fancy_face.c:626: tap 2 1
[INFO] fancy_face.c:632: before set 3 1
[INFO] fancy_face.c:634: after set 5 1
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 0 1
[INFO] fancy_face.c:634: after set 1 1
[INFO] fancy_face.c:626: tap 1 1
[INFO] fancy_face.c:632: before set 2 1
[INFO] fancy_face.c:634: after set 2 1
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 3 1
[INFO] fancy_face.c:634: after set 5 1
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:65 Showing configuration page: https://cdn.rawgit.com/johnmillage/FancyFace/f2da62db3d29b3a9c1a3f5bb1c53e61199138cb7/PebbleConfig.html
[PHONE] pebble-app.js:?: {'runhost client uuid' = 0630fde4-93a2-4dbd-93ba-4063bf3ca30a}:{'webapp uuid' = 0630fde4-93a2-4dbd-93ba-4063bf3ca30a}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = 0630fde4-93a2-4dbd-93ba-4063bf3ca30a}:{'webapp uuid' = 0630fde4-93a2-4dbd-93ba-4063bf3ca30a}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:72 Configuration page returned: {"background_color":"Black","temperature_type":"Fahrenheit"}
[INFO] fancy_face.c:667: got 3
[INFO] fancy_face.c:667: got 2
[INFO] fancy_face.c:667: got 4
[INFO] fancy_face.c:667: got 1
[INFO] fancy_face.c:667: got 0
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:91 Send successful: {"PHONE_COLOR_KEY":4,"PHONE_TEMP_TYPE_KEY":0}
[INFO] fancy_face.c:626: tap 2 1
[INFO] fancy_face.c:632: before set 2 4
[INFO] fancy_face.c:634: after set 1 4
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 2 4
[INFO] fancy_face.c:634: after set 1 4
[INFO] fancy_face.c:626: tap 2 1
[INFO] fancy_face.c:632: before set 2 4
[INFO] fancy_face.c:634: after set 1 4
[INFO] fancy_face.c:626: tap 2 1
[INFO] fancy_face.c:632: before set 2 4
[INFO] fancy_face.c:634: after set 1 4
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:65 Showing configuration page: https://cdn.rawgit.com/johnmillage/FancyFace/f2da62db3d29b3a9c1a3f5bb1c53e61199138cb7/PebbleConfig.html
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:65 Showing configuration page: https://cdn.rawgit.com/johnmillage/FancyFace/f2da62db3d29b3a9c1a3f5bb1c53e61199138cb7/PebbleConfig.html
[PHONE] pebble-app.js:?: {'runhost client uuid' = e1b3a33c-6f8a-473b-90b2-8a81e2229962}:{'webapp uuid' = e1b3a33c-6f8a-473b-90b2-8a81e2229962}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = d5cc5d7d-5644-4eb9-b1e6-73922d7db8b8}:{'webapp uuid' = d5cc5d7d-5644-4eb9-b1e6-73922d7db8b8}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:65 Showing configuration page: https://cdn.rawgit.com/johnmillage/FancyFace/f2da62db3d29b3a9c1a3f5bb1c53e61199138cb7/PebbleConfig.html
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:65 Showing configuration page: https://cdn.rawgit.com/johnmillage/FancyFace/f2da62db3d29b3a9c1a3f5bb1c53e61199138cb7/PebbleConfig.html
[INFO] fancy_face.c:626: tap 2 1
[INFO] fancy_face.c:632: before set 2 4
[INFO] fancy_face.c:634: after set 1 4
[PHONE] pebble-app.js:?: {'runhost client uuid' = d1254fc3-298e-457c-856c-aba0a21fb7e5}:{'webapp uuid' = d1254fc3-298e-457c-856c-aba0a21fb7e5}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = 9376c9ef-3ada-4cb3-aef8-8f5212a1d20c}:{'webapp uuid' = 9376c9ef-3ada-4cb3-aef8-8f5212a1d20c}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = 9376c9ef-3ada-4cb3-aef8-8f5212a1d20c}:{'webapp uuid' = 9376c9ef-3ada-4cb3-aef8-8f5212a1d20c}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:72 Configuration page returned: {"background_color":"Lights","temperature_type":"Fahrenheit"}
[INFO] fancy_face.c:667: got 3
[INFO] fancy_face.c:667: got 2
[INFO] fancy_face.c:667: got 4
[INFO] fancy_face.c:667: got 1
[INFO] fancy_face.c:667: got 0
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:91 Send successful: {"PHONE_COLOR_KEY":2,"PHONE_TEMP_TYPE_KEY":0}
[INFO] fancy_face.c:626: tap 2 1
[INFO] fancy_face.c:632: before set 4 2
[INFO] fancy_face.c:634: after set 4 2
[INFO] fancy_face.c:626: tap 2 1
[INFO] fancy_face.c:632: before set 5 2
[INFO] fancy_face.c:634: after set 0 2
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 1 2
[INFO] fancy_face.c:634: after set 3 2
[INFO] fancy_face.c:626: tap 0 1
[INFO] fancy_face.c:632: before set 4 2
[INFO] fancy_face.c:634: after set 4 2
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 5 2
[INFO] fancy_face.c:634: after set 0 2
[INFO] fancy_face.c:626: tap 0 1
[INFO] fancy_face.c:632: before set 1 2
[INFO] fancy_face.c:634: after set 3 2
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 4 2
[INFO] fancy_face.c:634: after set 4 2
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 5 2
[INFO] fancy_face.c:634: after set 0 2
[INFO] fancy_face.c:626: tap 2 1
[INFO] fancy_face.c:632: before set 1 2
[INFO] fancy_face.c:634: after set 3 2
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 4 2
[INFO] fancy_face.c:634: after set 4 2
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:65 Showing configuration page: https://cdn.rawgit.com/johnmillage/FancyFace/f2da62db3d29b3a9c1a3f5bb1c53e61199138cb7/PebbleConfig.html
[PHONE] pebble-app.js:?: {'runhost client uuid' = 974f567c-252b-428e-9f0d-fe4160e0fe9f}:{'webapp uuid' = 974f567c-252b-428e-9f0d-fe4160e0fe9f}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: {'runhost client uuid' = 974f567c-252b-428e-9f0d-fe4160e0fe9f}:{'webapp uuid' = 974f567c-252b-428e-9f0d-fe4160e0fe9f}: ++_JS_LIFECYCLE_++:KILLED
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:72 Configuration page returned: {"background_color":"Black","temperature_type":"Fahrenheit"}
[INFO] fancy_face.c:667: got 3
[INFO] fancy_face.c:667: got 2
[INFO] fancy_face.c:667: got 4
[INFO] fancy_face.c:667: got 1
[INFO] fancy_face.c:667: got 0
[PHONE] pebble-app.js:?: Fancy_Face__0.0/pebble-js-app.js:91 Send successful: {"PHONE_COLOR_KEY":4,"PHONE_TEMP_TYPE_KEY":0}
[INFO] fancy_face.c:626: tap 2 1
[INFO] fancy_face.c:632: before set 2 4
[INFO] fancy_face.c:634: after set 1 4
[INFO] fancy_face.c:626: tap 2 1
[INFO] fancy_face.c:632: before set 2 4
[INFO] fancy_face.c:634: after set 1 4
[INFO] fancy_face.c:626: tap 2 -1
[INFO] fancy_face.c:632: before set 2 4
[INFO] fancy_face.c:634: after set 1 4
[INFO] fancy_face.c:626: tap 0 -1
[INFO] fancy_face.c:632: before set 2 4
[INFO] fancy_face.c:634: after set 1 4

**Comment by amroibrahim** [comment]
sorry to waste your time.

**Comment by johnmillage** [comment]
No problem at all.  Maybe I will change to dark colors/light colors so
people know it will still cycle.
